# Generated by Django 5.1.7 on 2025-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=30)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='title',
        ),
    ]
