# Generated by Django 5.1.7 on 2025-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_app', '0002_streamplatform_rename_name_watchlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
