# Generated by Django 5.1.7 on 2025-04-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_app', '0003_alter_streamplatform_id_alter_watchlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='Movies_app.streamplatform'),
            preserve_default=False,
        ),
    ]
